
replicas: 1

podDisruptionBudget: #{}
  minAvailable: 0

deploymentStrategy:
  type: Recreate


image:
  pullPolicy: Always

testFramework:
  enabled: true
  imagePullPolicy: Always
  securityContext: {}
  containerSecurityContext: {}
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

securityContext:
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532
  fsGroup: 65532

containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
    - ALL
  seccompProfile:
    type: RuntimeDefault


downloadDashboardsImage:
  pullPolicy: Always

downloadDashboards:
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 65532
    runAsGroup: 65532
    fsGroup: 65532
    capabilities:
      drop:
      - ALL
    seccompProfile:
      type: RuntimeDefault

resources:
 limits:
   cpu: 100m
   memory: 128Mi
 requests:
   cpu: 100m
   memory: 128Mi

nodeSelector:
  nodegroup: management-arm-rkt-mng

tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "management"
    effect: "NoSchedule"

persistence:
  type: pvc
  enabled: true
  storageClassName: "prod-i01-aws-us-east-2-efs-csi-dynamic-storage"
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  finalizers:
    - kubernetes.io/pvc-protection
  existingClaim: grafana-efs-pvc

initChownData:
  enabled: false

envFromSecret: "grafana-oauth-secrets"

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server.observe.svc.cluster.local
      access: proxy
      isDefault: true

grafana.ini:
  server:
    root_url: https://grafana.prod-i01-aws-us-east-2.twplatformlabs.org

sidecar:
  imagePullPolicy: Always
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 50m
      memory: 50Mi
  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 65532
    runAsGroup: 65532
    fsGroup: 65532
    capabilities:
      drop:
      - ALL
    seccompProfile:
      type: RuntimeDefault

assertNoLeakedSecrets: false