apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: observe
  labels:
    app: debug
spec:
  containers:
  - name: debug
    image: curlimages/curl:latest
    command: ["sleep", "infinity"]
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 100m
        memory: 128Mi