fullnameOverride: prometheus-alertmanager-oauth2-proxy

virtualService:
  hosts: alertmanager.prod-i01-aws-us-east-2.twplatformlabs.org
  gateways: istio-system/prod-i01-aws-us-east-2-twplatformlabs-org-gateway
  matchUrl: /oauth2/

authApp:
  name: prometheus-alertmanager
  upstream: http://prometheus-alertmanager.observe.svc.cluster.local:9093

tenant: https://pskctl.us.auth0.com/

