fullnameOverride: prometheus-server-oauth2-proxy

virtualService:
  hosts: prometheus.prod-i01-aws-us-east-2.twplatformlabs.org
  gateways: istio-system/prod-i01-aws-us-east-2-twplatformlabs-org-gateway
  matchUrl: /oauth2/

authApp:
  name: prometheus-server
  upstream: http://prometheus-server.observe.svc.cluster.local:80

tenant: https://pskctl.us.auth0.com/
