configmapReload:
  prometheus:
    enabled: false

server:
  image:
    pullPolicy: Always
  nodeSelector:
    nodegroup: management-arm-rkt-mng
  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "management"
      effect: "NoSchedule"
  podDisruptionBudget:
    enabled: true
    minAvailable: 0
  persistentVolume:
    enabled: true
    accessModes:
      - ReadWriteOnce
    existingClaim: "prometheus-efs-pvc"
    mountPath: /data
    size: 8Gi
    storageClass: "sbx-i01-aws-us-east-1-efs-csi-dynamic-storage"
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 512Mi
  securityContext:
    runAsUser: 65532
    runAsNonRoot: true
    runAsGroup: 65532
    fsGroup: 65532
    seccompProfile:
      type: "RuntimeDefault"
  containerSecurityContext:
    runAsUser: 65532
    runAsNonRoot: true
    runAsGroup: 65532
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
  service:
    enabled: true
  retention: "7d"
  retentionSize: "7GB"

  # these settings are to del with the fact that Prometeus doesn't support EFS
  extraArgs:
    storage.tsdb.min-block-duration: 15m
    storage.tsdb.max-block-duration: 15m
  lifecycle:
    postStart:
      exec:
        command: ["bash", "-c", "rm -rf /data/wal"]

serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: 'kubernetes-apiservers'
        kubernetes_sd_configs:
          - role: endpointslice


alertmanager:
  enabled: true
  image:
    pullPolicy: Always
  podDisruptionBudget:
    minAvailable: 0
  persistence:
    size: 4Gi
    storageClass: "sbx-i01-aws-us-east-1-efs-csi-dynamic-storage"
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi
  podSecurityContext:
    runAsUser: 65532
    runAsNonRoot: true
    runAsGroup: 65532
    fsGroup: 65532
  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop: ["ALL"]
    seccompProfile:
      type: RuntimeDefault
  nodeSelector:
    nodegroup: management-arm-rkt-mng
  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "management"
      effect: "NoSchedule"

kube-state-metrics:
  enabled: false

prometheus-node-exporter:
  enabled: true
  image:
    pullPolicy: Always
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi
  containerSecurityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsUser: 65532
    runAsNonRoot: true
    runAsGroup: 65532
    seccompProfile:
      type: RuntimeDefault
  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "management"
      effect: "NoSchedule"

prometheus-pushgateway:
  enabled: false
