apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oauth2-proxy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oauth2-proxy.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "oauth2-proxy.selectorLabels" . | nindent 6 }}
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "oauth2-proxy.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "oauth2-proxy.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:v{{ include "oauth2-proxy.tag" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --http-address=0.0.0.0:4180
            - --skip-provider-button=true
          ports:
            - name: {{ .Values.service.name | default "http" }}
              containerPort: {{ .Values.service.targetPort | default 80 }}
              protocol: {{ .Values.service.protocol | default "TCP" }}
          envFrom:
            - secretRef:
                name: {{ include "oauth2-proxy.fullname" . }}-secrets
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /ping
              port: 4180
            initialDelaySeconds: 0
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /ready
              port: 4180
            initialDelaySeconds: 0
            timeoutSeconds: 5
            successThreshold: 1
            periodSeconds: 10
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}  
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
