---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oauth2-proxy.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oauth2-proxy.labels" . | nindent 4 }}
stringData:
  OAUTH2_PROXY_UPSTREAMS: "{{ .Values.authApp.upstream }}"
  OAUTH2_PROXY_PROVIDER_DISPLAY_NAME: "auth0"
  OAUTH2_PROXY_PROVIDER: "oidc" 
  OAUTH2_PROXY_OIDC_ISSUER_URL: "{{ .Values.tenant }}"
  OAUTH2_PROXY_CLIENT_ID: "{{ .Values.env.OAUTH2_PROXY_CLIENT_ID }}"
  OAUTH2_PROXY_CLIENT_SECRET: "{{ .Values.env.OAUTH2_PROXY_CLIENT_SECRET }}"
  OAUTH2_PROXY_PASS_ACCESS_TOKEN: "true" 
  OAUTH2_PROXY_EMAIL_DOMAINS: "*" 
  OAUTH2_PROXY_REDIRECT_URL: "https://{{ .Values.virtualService.hosts }}/oauth2/callback"
  OAUTH2_PROXY_COOKIE_SECRET: "{{ .Values.env.OAUTH2_PROXY_COOKIE_SECRET }}"
