apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "oauth2-proxy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oauth2-proxy.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
{{ tpl ( toYaml . ) $ | indent 4 }}
  {{- end }}
automountServiceAccountToken: true
