apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "oauth2-proxy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oauth2-proxy.labels" . | nindent 4 }}
spec:
  hosts:
    - {{ .Values.virtualService.hosts }}
  gateways:
    - {{ .Values.virtualService.gateways }}
  http:
    - match:
        - uri:
            prefix: {{ .Values.virtualService.matchUrl }}
      route:
        - destination:
            host: {{ include "oauth2-proxy.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: {{ .Values.service.port | default 80 }}
    - route:
      - destination:
          host: {{ include "oauth2-proxy.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
          port:
            number: {{ .Values.service.port | default 80 }}
