---
apiVersion: v1
kind: Namespace
metadata:
  name: observe
  labels:
    istio-injection: enabled
    pod-security.kubernetes.io/audit: baseline

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: observe-ns-quota
  namespace: observe
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 4Gi
    limits.cpu: "20"
    limits.memory: 30Gi